[package]
name = "substrate-metadata"
version = "0.1.0"
authors = ["Bryan Chen <xlchen1291@gmail.com>"]
edition = "2018"

[dependencies]
parity-codec = { version = "3.0", default-features = false }
parity-codec-derive = { version = "3.0", default-features = false }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
rstd = { package="sr-std", path = "../sr-std", default-features = false }
primitive-types = { version = "0.2", default-features = false, features = ["codec"] }

[dev-dependencies]
substrate-metadata-derive = { path = "../metadata-derive" }

[features]
default = ["std"]
std = [
	"primitive-types/std",
	"primitive-types/serde",
	"primitive-types/heapsize",
	"primitive-types/byteorder",
	"primitive-types/rustc-hex",
	"primitive-types/libc",
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	"parity-codec-derive/std",
	"rstd/std",
]
nightly = []
strict = []
