[package]
name = "substrate-metadata"
version = "0.1.0"
authors = ["Bryan Chen <xlchen1291@gmail.com>"]

[dependencies]
parity-codec = { git = "https://github.com/paritytech/parity-codec.git", default-features = false }
parity-codec-derive = { version = "2.1", default-features = false }
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
sr-std = { path = "../sr-std", default-features = false }

[features]
default = ["std"]
std = [
	"serde/std",
	"serde_derive",
	"parity-codec/std",
	"parity-codec-derive/std",
	"sr-std/std",
]
nightly = []
strict = []
